---
title: "European Heart Journal Code and Data sharing practices"
output:
  rmarkdown::pdf_document:
    fig_caption: yes        
    includes:  
      in_header: my_header.tex
---

```{r setup, include=FALSE}
.libPaths('./lib')
library(rcrossref, lib.loc='./lib')
library(rtransparent,lib.loc='./lib')
library(oddpub,lib.loc='./lib')
library(metareadr,lib.loc='./lib')
library(stringr, lib.loc='./lib')
library(plyr, lib.loc='./lib')
library(crminer)
library(beepr, lib.loc='./lib')
library(readr)
#library(tidyverse)

old_path <- Sys.getenv("PATH")
Sys.setenv(PATH = paste(old_path, "/opt/homebrew/bin", sep = ":"))

# Extract txt from pdf
setwd("~/Desktop/test cardio")

df=read_csv('./output/codesharing.csv') %>% select(2,4)



```




```{r table1, echo=FALSE, fig.cap="Table 1. Data sharing practices in publications of EHJ",fig.height = 5, fig.width = 5}
tabl=table(df$is_open_data)
rownames(tabl)=c('Do not share data','Share data')
knitr::kable(tabl, col.names=c('Data sharing status','Occurrences'), caption="Data sharing practices in publications of EHJ")
```


```{r table2, echo=FALSE, fig.cap="Table 2. Code sharing practices in publications of EHJ",fig.height = 5, fig.width = 5}

tablz=table(df$is_open_code)
rownames(tablz)=c('Do not share code','Share code')
knitr::kable(tablz, col.names=c('Code sharing status','Occurrences'), caption="Code sharing practices in publications of EHJ")

```

